### ISSUE TITLE
Kaiwa doesn’t build?

### ISSUE THREAD

**Issue by michalrus** [svanderburg/node2nix#101]
Hello!

```
$ git clone https://github.com/ForNeVeR/Kaiwa.git
$ cd Kaiwa
$ node2nix -d --strip-optional-dependencies
$ cat >overriden.nix
(import ./default.nix {}).package.overrideAttrs (drv: {
  postInstall = "npm run compile";
})

$ nix-build overriden.nix
```

Results in:

```
[...]
[10:05:34] Starting 'jade-views'...
[10:05:34] Finished 'jade-views' after 444 ms
[10:05:34] Finished 'resources' after 1.63 s
[10:05:34] Finished 'jade-templates' after 1.63 s
[10:05:34] Starting 'client'...

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./src/js/app.ts
Module parse failed: /nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/src/js/app.ts Unexpected token (6:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (6:8)
    at Parser.pp$4.raise (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/node_modules/webpack/lib/NormalModule.js:104:16)

npm ERR! Linux 4.14.54
npm ERR! argv "/nix/store/8icflc0s2g28016wn68iysmbmyn3nn51-nodejs-6.14.3/bin/node" "/nix/store/8icflc0s2g28016wn68iysmbmyn3nn51-nodejs-6.14.3/bin/npm" "run" "compile"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kaiwa.im@1.1.0 compile: `gulp compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kaiwa.im@1.1.0 compile script 'gulp compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kaiwa.im package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kaiwa.im
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kaiwa.im
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /nix/store/d1iy33xv645983v6ndwda1dwbb5d99ha-node-kaiwa.im-1.1.0/lib/node_modules/kaiwa.im/npm-debug.log
builder for '/nix/store/gk53jbrbprf5yg3sqn4lim2xsaw3q69j-node-kaiwa.im-1.1.0.drv' failed with exit code 1
error: build of '/nix/store/gk53jbrbprf5yg3sqn4lim2xsaw3q69j-node-kaiwa.im-1.1.0.drv' failed
```

-------

Also, why is `gulp: command not found` in `nix-shell -A shell`, if I called `node2nix` with `-d`?

**Comment by svanderburg** [comment]
I think the problem is indeed caused by the fact that `gulp` is not in the `PATH` of the build environment. Can you add a `supplement.json` configuration file with `gulp` as a dependency and regenerate the Nix expressions again?

The `README.md` file has a section that explains how to provide supplement packages using `grunt` as an example. I think it's relatively easy to repeat with `gulp`.

**Comment by michalrus** [comment]
It think it’s not that, which makes it even weirder…

In the log above, you can see successful completion of these tasks:

```
[10:05:34] Starting 'jade-views'...
[10:05:34] Finished 'jade-views' after 444 ms
[10:05:34] Finished 'resources' after 1.63 s
[10:05:34] Finished 'jade-templates' after 1.63 s
[10:05:34] Starting 'client'...
```

While they are defined in `Gulpfile.js`:

https://github.com/ForNeVeR/Kaiwa/blob/a86d4080994d49e5e6195188e7fda230ba66d437/Gulpfile.js#L99-L101

It’s the `client` Gulp task that fails.

Perhaps you could try those 5 commands I posted above on your machine? :pray:

**Comment by svanderburg** [comment]
This is actually quite a difficult/annoying problem. It took me a bit of experimentation to figure out what is going on.

If I change the following file:

```diff
diff --git a/webpack.config.js b/webpack.config.js
index 49d2ae3..7e52042 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -49,7 +49,7 @@ module.exports = {
             },
             {
                 test: /\.ts(x?)$/,
-                exclude: /(node_modules|bower_components|libraries)/,
+                exclude: /(bower_components|libraries)/,
                 loader: 'babel!ts-loader'
             },
             {
```

Then it seems to work.

I think the problem is caused by the fact that in a Nix builder environment, the project is moved to `$out/lib/node_modules/<project name>` first, and inside that directory, the builder will run NPM. Because there is a `node_modules/` component in the absolute path, I think it probably gets excluded and as a result, the `babel-preset-es2015` refuses to do the translation.

In a future version of `node2nix`, I may have to reconsider the packaging strategy in such a way that the project is not copied into a `node_modules/` folder first.

**Comment by michalrus** [comment]
Thank you for the investigation, now it works indeed!

I’ll leave the decision on closing this issue to you.
