### ISSUE TITLE
Fails for project with no 'name' field specified

### ISSUE THREAD

**Issue by kubek2k** [svanderburg/node2nix#103]
When trying to generate nix expression for a package.json with no `name` specified, it fails with:

```
: /tmp/cli (master %) $ node2nix
fetching local directory: ./. from .
/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124
        name: this.config.name.replace("@", "_at_").replace("/", "_slash_"), // Escape characters from scoped package names that aren't allowed
                              ^

TypeError: Cannot read property 'replace' of undefined
    at LocalSource.Source.toNixAST (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124:31)
    at LocalSource.toNixAST (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/LocalSource.js:99:41)
    at Package.toNixAST (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/Package.js:324:27)
    at Package.NixASTNode.toNixExpr (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixASTNode.js:44:38)
    at jsToIndentedNix (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at Object.objectMembersToAttrsMembers (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:101:52)
    at NixLet.toNixExpr (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixLet.js:32:14)
    at Object.jsToIndentedNix (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at NixFunction.toNixExpr (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixFunction.js:81:18)
    at Object.jsToIndentedNix (/nix/store/dhgfrgp5bkqjw86ynficf9k1bpjq7fbx-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
```

I think it should catch those earlier (Source constructor?)

**Comment by svanderburg** [comment]
I added a name and version check in revision 91b2dd583cd127ff1a6f1447e7f1e4982980c584
