### ISSUE TITLE
 TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Rizary** [svanderburg/node2nix#130]
I am still having the `cannot read property 'replace' of undefined` error even after this https://github.com/svanderburg/node2nix/issues/47 issue suggestion.

```
node2nix -l package-lock.json --nodejs-8

fetching local directory: ./. from .
/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124
        name: this.config.name.replace("@", "_at_").replace("/", "_slash_"), // Escape characters from scoped package names that aren't allowed
                               ^

TypeError: Cannot read property 'replace' of undefined
    at LocalSource.Source.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124:32)
    at LocalSource.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/LocalSource.js:99:41)
    at Package.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/Package.js:324:27)
    at Package.NixASTNode.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixASTNode.js:44:38)
    at jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at Object.objectMembersToAttrsMembers (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:101:52)
    at NixLet.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixLet.js:32:14)
    at Object.jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at NixFunction.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixFunction.js:81:18)
    at Object.jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
```

This is my `package.json` looks like:
```
{
  "private": true,
  "scripts": {
    "start": "webpack-dev-server"
  },
  "dependencies": {
    "@babel/core": "^7.1.2",
    "fable-compiler": "^2.1.3",
    "fable-loader": "^2.1.0",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10",
    "react": "^16.6.0",
    "react-dom": "^16.6.0"
  }
}
```
I tried with only `package.json` and got the following error after this `node2nix -i package.json --nodejs-10 --supplement-input supplement.json `:
```
http request GET http://registry.npmjs.org/scheduler
http 200 http://registry.npmjs.org/scheduler
/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124
        name: this.config.name.replace("@", "_at_").replace("/", "_slash_"), // Escape characters from scoped package names that aren't allowed
                               ^

TypeError: Cannot read property 'replace' of undefined
    at LocalSource.Source.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124:32)
    at LocalSource.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/LocalSource.js:99:41)
    at Package.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/Package.js:324:27)
    at Package.NixASTNode.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixASTNode.js:44:38)
    at jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at Object.objectMembersToAttrsMembers (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:101:52)
    at NixLet.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixLet.js:32:14)
    at Object.jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at NixFunction.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixFunction.js:81:18)
    at Object.jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
```

I can't find which package caused the problem.

**Comment by spinus** [comment]
I confirm the issue. How could we solve that? Would providing "default" name breaks anything?

**Comment by kuznero** [comment]
Can see exactly the same behavior

**Comment by kuznero** [comment]
I cannot find a way to easily fix it. `nix-shell -A shell` or `nix-build -A package` result in an error. Any guidelines on how to get started with a PR would be great!

**Comment by svanderburg** [comment]
The `package.json` file (shown above) has no name property set. In such configuration files, name and version attributes are required.

The current development version contains a check for this and notifies the user.

**Comment by svanderburg** [comment]
node2nix 1.7.0 should warn you when the name or version property in missing in package.json.

**Comment by Rizary** [comment]
@svanderburg thank you. So it is happened to certain conditions or all `package.json` should contain name property? because in other project, I dont need to put name in `package.json`

**Comment by svanderburg** [comment]
@Rizary all package.json files should. Unless something has changed recently, this is a hard requirement according to the documentation provided by NPM.

**Comment by svanderburg** [comment]
I'm closing this, because the check should not now at least explain the user that these mandatory properties are missing.
