### ISSUE TITLE
node2nix fails to package bash-language-server 

### ISSUE THREAD

**Issue by Luis-Hebendanz** [svanderburg/node2nix#156]
When I execute `node2nix` in the [bash-language-server](https://github.com/mads-hartmann/bash-language-server) repo I get the following stack trace:

```                                        
fetching local directory: ./. from .
/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124
        name: this.config.name.replace("@", "_at_").replace("/", "_slash_"), // Escape characters from scoped package names that aren't allowed
                               ^

TypeError: Cannot read property 'replace' of undefined
    at LocalSource.Source.toNixAST (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124:32)
    at LocalSource.toNixAST (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/LocalSource.js:99:41)
    at Package.toNixAST (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/Package.js:324:27)
    at Package.NixASTNode.toNixExpr (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixASTNode.js:44:38)
    at jsToIndentedNix (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at Object.objectMembersToAttrsMembers (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:101:52)
    at NixLet.toNixExpr (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixLet.js:32:14)
    at Object.jsToIndentedNix (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at NixFunction.toNixExpr (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixFunction.js:81:18)
    at Object.jsToIndentedNix (/nix/store/haka30md3560jrz0jnlkgha22inlgrxk-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)

```

**Comment by chkl** [comment]
I stumbled upon the same issue. What fixed it for me was to define `name`  in the `package.json`. Apparently npm does not strictly require the field, but node2nix does.
