### ISSUE TITLE
How can node2nix be built?

### ISSUE THREAD

**Issue by codygman** [svanderburg/node2nix#173]
First try, just running bootstrap.sh:

```shell
[cody@nixos:/tmp/node2nix]$ ./bootstrap.sh      
./bootstrap.sh: line 13: node: command not found
```

Second try, start a nix-shell with nodejs and run bootstrap:

```shell
[cody@nixos:/tmp/node2nix]$ nix-shell -p nodejs

[nix-shell:/tmp/node2nix]$ ./bootstrap.sh 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'optparse'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/node2nix/bin/node2nix.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I see it wants nodejs 8, but I don't see a quick easy way to add nodejs 8 since it's not present with a nox search:

```shell
[nix-shell:/tmp/node2nix]$ nox nodejs
Refreshing cache
1 hxnodejs-4.0.9 (nixos.haxePackages.hxnodejs_4)
    Extern definitions for node.js 4.x
2 hxnodejs-6.9.0 (nixos.haxePackages.hxnodejs_6)
    Extern definitions for node.js 6.9
3 nodejs-10.18.1 (nixos.nodejs)
    Event-driven I/O framework for the V8 JavaScript engine
4 nodejs-10.18.1 (nixos.nodejs-10_x)
    Event-driven I/O framework for the V8 JavaScript engine
5 nodejs-12.14.1 (nixos.nodejs-12_x)
    Event-driven I/O framework for the V8 JavaScript engine
6 nodejs-13.7.0 (nixos.nodejs-13_x)
    Event-driven I/O framework for the V8 JavaScript engine
7 nodejs-slim-10.18.1 (nixos.nodejs-slim)
    Event-driven I/O framework for the V8 JavaScript engine
8 nodejs-slim-12.14.1 (nixos.nodejs-slim-12_x)
    Event-driven I/O framework for the V8 JavaScript engine
9 nodejs-slim-13.7.0 (nixos.nodejs-slim-13_x)
    Event-driven I/O framework for the V8 JavaScript engine
Packages to install:   C-c C-cAborted!
```

I open up the bootstrap.sh file and I see:

```
# This script generates the Nix expressions for node2nix itself and its
# testcases.
# It can be invoked by installing its dependencies first, by either running:
#
# $ npm install
#
# or by starting a Nix shell:
#
# $ nix-shell -A shell
```

Oh okay, so I need to use the nix-shell with attrPath shell? Let's try that:

```
[nix-shell:/tmp/node2nix]$ nix-shell -A shell
error: attribute 'nodejs-8_x' missing, at /tmp/node2nix/default.nix:5:48
(use '--show-trace' to show detailed location information)
```

I guess that means I can't build node2nix with `NixOS 20.03pre211190.a21c2fa3ea2` by default?

**Comment by svanderburg** [comment]
Good question. It is mostly obvious for seasoned Nix users, but I think it would not hurt to explicitly describe it in the README. In e976026122ceb767e6417c342777e749d5883226 I have added a description.

**Comment by svanderburg** [comment]
Closing this, because I believe this change addresses the problem
