### ISSUE TITLE
Typescript output missing in output path

### ISSUE THREAD

**Issue by mweinelt** [svanderburg/node2nix#183]
The matrix-appservice-irc uses typescript and generates output from the `./src into the `./lib` folder of the project.

https://github.com/matrix-org/matrix-appservice-irc/blob/master/tsconfig.json#L10

That `./lib` directory is not part of the result, hence the `matrix-appservice-irc` binary is unable to include files from there.

```
Error: Cannot find module './lib/logging'
Require stack:
- /nix/store/ndj8lhmrz21df8cgvjaw87hbkvzxr0zg-node_matrix-appservice-irc-0.17.1/lib/node_modules/matrix-appservice-irc/app.js
- /nix/store/ndj8lhmrz21df8cgvjaw87hbkvzxr0zg-node_matrix-appservice-irc-0.17.1/lib/node_modules/matrix-appservice-irc/bin/matrix-appservice-irc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/nix/store/ndj8lhmrz21df8cgvjaw87hbkvzxr0zg-node_matrix-appservice-irc-0.17.1/lib/node_modules/matrix-appservice-irc/app.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/nix/store/ndj8lhmrz21df8cgvjaw87hbkvzxr0zg-node_matrix-appservice-irc-0.17.1/lib/node_modules/matrix-appservice-irc/bin/matrix-appservice-irc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/ndj8lhmrz21df8cgvjaw87hbkvzxr0zg-node_matrix-appservice-irc-0.17.1/lib/node_modules/matrix-appservice-irc/app.js',
    '/nix/store/ndj8lhmrz21df8cgvjaw87hbkvzxr0zg-node_matrix-appservice-irc-0.17.1/lib/node_modules/matrix-appservice-irc/bin/matrix-appservice-irc'
  ]
}
```

**Comment by mweinelt** [comment]
My bad. I should always use `package.json` as the `--input``because that is where the build steps are defined.
