### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/homeless-shelter'

### ISSUE THREAD

**Issue by Rizary** [svanderburg/node2nix#217]
Hi!

This is my `default.nix`:

```
{pkgs ? import <nixpkgs> { inherit system; }, system ? builtins.currentSystem }:
let
  nodeDependencies = (pkgs.callPackage ./compose.nix {}).shell.nodeDependencies;
in
with pkgs;
stdenv.mkDerivation {
  name = "rollup-wasm-nix";
  src = ./.;
  buildInputs = [nodejs];
  buildPhase = ''
    ln -s ${nodeDependencies}/lib/node_modules ./node_modules
    export PATH="${nodeDependencies}/bin:$PATH"

    # Build the distribution bundle in "dist"
    npm run build
    cp -r dist $out/
  '';
}
```

I try to build WebAssembly project with `wasm-pack`. According to this: https://github.com/rustwasm/wasm-pack/blob/master/npm/binary.js#L22, it seems `wasm-pack` uses `binary-install` package to download and install its binary.

And in my `package.json` it only runs: `"build": "rollup -c rollup.prod.js"` script. And that's it, running `nix-build` got the following error:

```
> rollup -c rollup.prod.js


./Cargo.toml → js...
/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/mkdirp/index.js:91
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/homeless-shelter'
    at Object.mkdirSync (fs.js:987:3)
    at sync (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/mkdirp/index.js:72:13)
    at sync (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/mkdirp/index.js:78:24)
    at Function.sync (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/mkdirp/index.js:78:24)
    at Binary._getInstallDirectory (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/binary-install/src/binary.js:49:14)
    at Binary._getBinaryDirectory (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/binary-install/src/binary.js:55:35)
    at Binary._getBinaryPath (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/binary-install/src/binary.js:67:36)
    at Binary.run (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/binary-install/src/binary.js:123:29)
    at run (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/wasm-pack/binary.js:33:10)
    at Object.<anonymous> (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/wasm-pack/run.js:4:1) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/homeless-shelter'
}
[!] (plugin rust) Error: Command `wasm-pack --log-level info build --out-dir /tmp/nix-build-rollup-wasm-nix.drv-0/rollup-wasm-nix/target/wasm-pack/rust-frontend --out-name index --target web --release --` failed with error code: 1
Cargo.toml
Error: Command `wasm-pack --log-level info build --out-dir /tmp/nix-build-rollup-wasm-nix.drv-0/rollup-wasm-nix/target/wasm-pack/rust-frontend --out-name index --target web --release --` failed with error code: 1
    at ChildProcess.<anonymous> (/nix/store/scqx8fm2c7d2miv6h4k95jmw0xxv7vnz-node-dependencies-rust-0.1.0/lib/node_modules/@wasm-tool/rollup-plugin-rust/index.js:81:24)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rust@0.1.0 build: `rollup -c rollup.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rust@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Rizary** [comment]
It solved by adding:

```
export HOME=$(mktemp -d)
```

in the `buildPhase`
