### ISSUE TITLE
`TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string.` when trying to covert growi

### ISSUE THREAD

**Issue by cyber-murmel** [svanderburg/node2nix#234]
NixOS version: 20.09
```
$ node2nix --version
node2nix 1.8.0
```

I tried to use node2nix in order to build [growi](https://github.com/weseek/growi), but I get this error.
```
$ git clone https://github.com/weseek/growi
$ cd growi/
$ node2nix
fetching local directory: ./. from .
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Array
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Function.Source.constructSource (/nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/lib/sources/Source.js:49:25)
    at new Package (/nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/lib/Package.js:37:26)
    at /nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/lib/Package.js:154:27
    at Array.<anonymous> (/nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:221:29)
    at runStatement (/nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:24:25)
    at sequence (/nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:51:9)
    at Array.<anonymous> (/nix/store/46dimjisy6z5b7w80m6z4jhxgq0djjxq-node_node2nix-1.8.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:219:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
I don't know how to interpret this error or how to debug it :/

**Comment by cyber-murmel** [comment]
Oh, I looked around and saw that [the first lines of the `dependencies` in the package.json](https://github.com/weseek/growi/blob/master/package.json#L73) are garbarge.
Is this a problem on their side or should node2nix ignore these lines?
