### ISSUE TITLE
`tests.cli` fails: Exception: command `cd testprojects/noversion; node2nix` unexpectedly succeeded

### ISSUE THREAD

**Issue by andersk** [svanderburg/node2nix#271]
As of commit 5ebb644c37fb3b6ecdd2a21692381d2fbd6ccd7a, the `tests.cli` test fails:

```console
$ nix-build release.nix -A tests.cli
…
machine # Mandatory name attribute is missing in package.json
(2.13 seconds)
machine: must fail: cd testprojects/noversion; node2nix
machine # fetching local directory: ./. from .
cleanup
kill machine (pid 8)
machine # qemu-system-x86_64: terminating on signal 15 from pid 6 (/nix/store/8dxxjbiyxwkvh53q5kh6nydla2anacgi-python3-3.9.6/bin/python3)
(0.05 seconds)
Traceback (most recent call last):
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1334, in <module>
    driver.run_tests()
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1210, in run_tests
    self.test_script()
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 1206, in test_script
    exec(self.tests, symbols, None)
  File "<string>", line 12, in <module>
  File "/nix/store/6w9rwx6y58r9i3jfh8lq7fi6gdbq59bg-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 653, in fail
    raise Exception(
Exception: command `cd testprojects/noversion; node2nix` unexpectedly succeeded
```

Perhaps consider arranging for the tests to run in GitHub Actions or another CI system, so that failures are caught quickly and automatically. This might require running `bootstrap.sh` more frequently, but that would be a win for usability of the Git version anyway.

**Comment by svanderburg** [comment]
Yes I need to re-run bootstrap again, that will fix the issue. I intend to this soon.
