### ISSUE TITLE
Overriding `src` argument for `package` doesn't work.

### ISSUE THREAD

**Issue by k0001** [svanderburg/node2nix#31]
If in `default.nix` one tries to override the `src` argument for the generated `nodePackages.package` using `nodePackages.package.override` as suggested in the tutorial, it doesn't really work. Instead, when trying to run `nix-build` one gets an error like this:

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './package.json'
```

Manually replacing the `src` argument inside the generated `args` in `node-packages.nix` does work, but of course that's not very convenient.

**Comment by k0001** [comment]
I would suggest that the generated `node-packages.nix` should export just `args`, instead of `package`, `shell` and `tarball`, seeing as those three can be constructed using the tools from `node-env.nix` as necessary.

**Comment by svanderburg** [comment]
Yes, currently this is a problem. I have to rethink the interface a bit so that overriding/extending in general becomes better.

**Comment by flosse** [comment]
Anything new here?

**Comment by svanderburg** [comment]
Not yet. I have been mostly working on fixing issue #26

**Comment by ck3d** [comment]
I could live with a package containing only the dependencies _node_modules_.

**Comment by svanderburg** [comment]
It's now probably possible to make this kind of override, since I made all node2nix function invocations overridable.

**Comment by Shou** [comment]
I'm not sure if this got into 1.6.0 because I'm having this issue with an `override.nix` in trying to contribute a new package to Nixpkgs. The full diff can be found [here](https://gist.github.com/Shou/7544e077bd5596d241499ea2da85b9e9) but hopefully you can ignore the autogenerated files.

```js
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/nix/store/y04w4j655f0wgb9n6yhva3ckm14hfmvk-pinpointDependencies.js:37:32)                                                                        
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```
