### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by arnm** [svanderburg/node2nix#47]
I ran `node2nix` on the following `package.json` and got this error:

```json
{
  "dependencies": {
    "ungit": "*"
  }
}
```

```
/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/lib/packageset.js:414
                name: metadata.packageObj.name.replace("@", "_at_").replace("/", "_slash_"), // Escape characters from scoped package names that aren't allowed
                                              ^

TypeError: Cannot read property 'replace' of undefined
    at Array.<anonymous> (/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/lib/packageset.js:414:47)
    at runStatement (/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:24:25)
    at /nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:28:21
    at runStatement (/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:22:17)
    at /nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:28:21
    at runStatement (/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:22:17)
    at /nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:28:21
    at runStatement (/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:22:17)
    at /nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:28:21
    at Array.<anonymous> (/nix/store/m8xlrix7a5fi4i0jm579jd8hf7zykkbr-node-node2nix-1.2.0/lib/node_modules/node2nix/node_modules/slasp/lib/slasp.js:82:25)
```

**Comment by svanderburg** [comment]
The correct way to install ungit as a package is by providing the following JSON file (e.g. `pkgs.json`):

```json
[
  { "ungit": "*" }
]
```

When providing an object as a root element in a JSON file, node2nix expects it to be a valid package.json config. A package.json config file requires a name and version attribute, which in your case are missing.

Maybe I should produce a more user-friendly message stating that these mandatory properties are missing.

**Comment by svanderburg** [comment]
I have added a check for this in revision 04b00adb2f2655afb1f7ef08125932052fc19d8a

Perhaps, it is not such a bad idea to warn the user.

**Comment by Rizary** [comment]
I am still having the `cannot read property 'replace' of undefined` error:

```
node2nix -l package-lock.json --nodejs-8

fetching local directory: ./. from .
/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124
        name: this.config.name.replace("@", "_at_").replace("/", "_slash_"), // Escape characters from scoped package names that aren't allowed
                               ^

TypeError: Cannot read property 'replace' of undefined
    at LocalSource.Source.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/Source.js:124:32)
    at LocalSource.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/sources/LocalSource.js:99:41)
    at Package.toNixAST (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/lib/Package.js:324:27)
    at Package.NixASTNode.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixASTNode.js:44:38)
    at jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at Object.objectMembersToAttrsMembers (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:101:52)
    at NixLet.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixLet.js:32:14)
    at Object.jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
    at NixFunction.toNixExpr (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/ast/NixFunction.js:81:18)
    at Object.jsToIndentedNix (/nix/store/rjqfgv4zqdwxyy9rgxbvaqh064cpkwnl-node-node2nix-1.6.0/lib/node_modules/node2nix/node_modules/nijs/lib/generate.js:233:37)
```
