### ISSUE TITLE
Unable to install purescript.

### ISSUE THREAD

**Issue by wpoosanguansit** [svanderburg/node2nix#52]
When I tried to install purescript, I do get the errors below:

to-executable-name@1.1.0 /nix/store/r96pm5y9kwmmgnw1gf9lacwszv24z5z3-node-purescript-0.11.5/lib/node_modules/purescript/node_modules/to-executable-name

> purescript@0.11.5 postinstall /nix/store/r96pm5y9kwmmgnw1gf9lacwszv24z5z3-node-purescript-0.11.5/lib/node_modules/purescript
> node lib/install.js

/nix/store/r96pm5y9kwmmgnw1gf9lacwszv24z5z3-node-purescript-0.11.5/lib/node_modules/purescript/lib/install.js:10
const {BASE_URL, SOURCE_URL} = require('.');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

npm ERR! Linux 4.8.0-54-generic
npm ERR! argv "/nix/store/h1smnbkylnwin3156bvkrswm9dhzp71a-nodejs-4.8.1/bin/node" "/nix/store/h1smnbkylnwin3156bvkrswm9dhzp71a-nodejs-4.8.1/bin/npm" "--registry" "http://www.example.com" "--nodedir=/nix/store/j318416wdprvb90848zrl3za17aqdr92-node-sources" "--production" "install"
npm ERR! node v4.8.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! purescript@0.11.5 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.11.5 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /nix/store/r96pm5y9kwmmgnw1gf9lacwszv24z5z3-node-purescript-0.11.5/lib/node_modules/purescript/npm-debug.log
builder for ‘/nix/store/8f1wbwij1062sj14m10h584njpaprhz7-node-purescript-0.11.5.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/gbf3v08pjfw737v2jkinyfrffs21fysq-nodejsEnv.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/gbf3v08pjfw737v2jkinyfrffs21fysq-nodejsEnv.drv’ failed

The offending line is:
 
const {BASE_URL, SOURCE_URL} = require('.');

However, when I install using straight npm install purescript, it went thru fine.  Is there a way to get around this error?  Thanks for your help.

**Comment by wpoosanguansit** [comment]
the issue is resolved as I mistakenly set the version incorrectly to 4.x instead of 6.x.
