### ISSUE TITLE
Storing generated expressions in a subdirectory

### ISSUE THREAD

**Issue by joepie91** [svanderburg/node2nix#53]
I'm trying to avoid cluttering up my project's root directory with Nix expressions, attempting to store the expressions in a `nix/` subfolder instead. However, this poses a problem during build:

```
pinpointing versions of dependencies...
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/nix/store/l1m3w8dc37qszk6k6mdkg3vh5jbhsvcn-pinpointDependencies.js:37:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

Presumably, it's using the `nix/` folder itself as the root of the build, rather than the project root that exists one level higher. Would it be possible to add an option to `node2nix` for storing the generated files in a subdirectory, and modifying the paths in the expressions accordingly?

**Comment by svanderburg** [comment]
In revision https://github.com/svanderburg/node2nix/commit/54be3f8a89afc0b4450c6713d26cc6b93d6c7c7d I changed the generation procedure for the composition expression so that it always properly composes the relative paths to the other expressions that it imports.

Maybe this change will also help you out.
