### ISSUE TITLE
Missing nix dependency

### ISSUE THREAD

**Issue by jluttine** [svanderburg/node2nix#58]
This is probably nixpkgs packaging issue, not an issue in node2nix itself perhaps, but I thought I'd mention it here just in case.

I get the following error:
```
$ nix-shell --pure -p nodePackages.node2nix
$ node2nix 
info attempt registry request try #1 at 8:48:04 PM
http request GET http://registry.npmjs.org/@iamadamjowett%2Fangular-click-outside
http 200 http://registry.npmjs.org/@iamadamjowett%2Fangular-click-outside
info attempt registry request try #1 at 8:48:05 PM
http request GET http://registry.npmjs.org/angular
http 200 http://registry.npmjs.org/angular
info attempt registry request try #1 at 8:48:05 PM
http request GET http://registry.npmjs.org/angular-cache
http 200 http://registry.npmjs.org/angular-cache
info attempt registry request try #1 at 8:48:05 PM
http request GET http://registry.npmjs.org/angular-route
http 200 http://registry.npmjs.org/angular-route
info attempt registry request try #1 at 8:48:05 PM
http request GET http://registry.npmjs.org/angular-sanitize
http 200 http://registry.npmjs.org/angular-sanitize
info attempt registry request try #1 at 8:48:06 PM
http request GET http://registry.npmjs.org/angular-ui-bootstrap
http 200 http://registry.npmjs.org/angular-ui-bootstrap
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nix-hash ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

However, if I add `nix` to the environment, it succeeds:
```
$ nix-shell --pure -p nodePackages.node2nix nix
$ node2nix 
info attempt registry request try #1 at 8:50:26 PM
http request GET http://registry.npmjs.org/@iamadamjowett%2Fangular-click-outside
http 200 http://registry.npmjs.org/@iamadamjowett%2Fangular-click-outside
info attempt registry request try #1 at 8:50:27 PM
http request GET http://registry.npmjs.org/angular
http 200 http://registry.npmjs.org/angular
info attempt registry request try #1 at 8:50:28 PM
http request GET http://registry.npmjs.org/angular-cache
http 200 http://registry.npmjs.org/angular-cache
info attempt registry request try #1 at 8:50:28 PM
http request GET http://registry.npmjs.org/angular-route
http 200 http://registry.npmjs.org/angular-route
info attempt registry request try #1 at 8:50:28 PM
http request GET http://registry.npmjs.org/angular-sanitize
http 200 http://registry.npmjs.org/angular-sanitize
info attempt registry request try #1 at 8:50:28 PM
http request GET http://registry.npmjs.org/angular-ui-bootstrap
http 200 http://registry.npmjs.org/angular-ui-bootstrap
info attempt registry request try #1 at 8:50:28 PM
http request GET http://registry.npmjs.org/angular-uuid4
http 200 http://registry.npmjs.org/angular-uuid4
info attempt registry request try #1 at 8:50:28 PM
http request GET http://registry.npmjs.org/jquery-timepicker
http 200 http://registry.npmjs.org/jquery-timepicker
info attempt registry request try #1 at 8:50:29 PM
http request GET http://registry.npmjs.org/ngclipboard
http 200 http://registry.npmjs.org/ngclipboard
info attempt registry request try #1 at 8:50:29 PM
http request GET http://registry.npmjs.org/ui-select
http 200 http://registry.npmjs.org/ui-select
info attempt registry request try #1 at 8:50:29 PM
http request GET http://registry.npmjs.org/vcard-parser
http 200 http://registry.npmjs.org/vcard-parser
info attempt registry request try #1 at 8:50:29 PM
http request GET http://registry.npmjs.org/jquery
http 200 http://registry.npmjs.org/jquery
info attempt registry request try #1 at 8:50:29 PM
http request GET http://registry.npmjs.org/clipboard
http 200 http://registry.npmjs.org/clipboard
info attempt registry request try #1 at 8:50:29 PM
http request GET http://registry.npmjs.org/good-listener
http 200 http://registry.npmjs.org/good-listener
info attempt registry request try #1 at 8:50:30 PM
http request GET http://registry.npmjs.org/select
http 200 http://registry.npmjs.org/select
info attempt registry request try #1 at 8:50:30 PM
http request GET http://registry.npmjs.org/tiny-emitter
http 200 http://registry.npmjs.org/tiny-emitter
info attempt registry request try #1 at 8:50:30 PM
http request GET http://registry.npmjs.org/delegate
http 200 http://registry.npmjs.org/delegate
```

The full package.json file
```
{
  "name": "contacts",
  "version": "2.0.1",
  "description": "Place this app in **nextcloud/apps/**",
  "author": {
    "name": "Hendrik Leppelsack",
    "email": "hendrik@leppelsack.de"
  },
  "private": true,
  "repository": {
    "type": "git",
    "url": "git+https://github.com/nextcloud/contacts.git"
  },
  "license": "AGPL-3.0",
  "bugs": {
    "url": "https://github.com/nextcloud/contacts/issues"
  },
  "homepage": "https://github.com/nextcloud/contacts#readme",
  "scripts": {
    "test": "node node_modules/gulp-cli/bin/gulp.js karma",
    "prebuild": "npm install && npm update",
    "build": "node node_modules/gulp-cli/bin/gulp.js",
    "scss-compile": "cat build/css/variables.scss css/style.scss | node-sass --include-path css > css/style.css",
    "watch": "node node_modules/gulp-cli/bin/gulp.js watch"
  },
  "devDependencies": {
    "angular-mocks": "~1.5.8",
    "chai": "^3.5.0",
    "codecov": "^1.0.1",
    "gulp": "^3.9.1",
    "gulp-cli": "^1.2.2",
    "gulp-concat": "^2.6.0",
    "gulp-eslint": "^3.0.1",
    "gulp-ng-annotate": "^2.0.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-stylelint": "^5.0.0",
    "karma": "^1.2.0",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.1.1",
    "karma-firefox-launcher": "^1.0.0",
    "karma-mocha": "^1.1.1",
    "karma-mocha-reporter": "^2.1.0",
    "karma-sinon": "^1.0.5",
    "merge-stream": "^1.0.1",
    "mocha": "^3.0.2",
    "node-sass": "^4.5.3",
    "sinon": "^1.17.5",
    "stylelint-config-standard": "^17.0.0",
    "underscore": "^1.8.3"
  },
  "dependencies": {
    "@iamadamjowett/angular-click-outside": "^2.10.1",
    "angular": "~1.5.8",
    "angular-cache": "^4.6.0",
    "angular-route": "~1.5.8",
    "angular-sanitize": "~1.5.8",
    "angular-ui-bootstrap": "^2.5.6",
    "angular-uuid4": "^0.3.1",
    "jquery-timepicker": "^1.3.3",
    "ngclipboard": "^1.1.2",
    "ui-select": "^0.19.8",
    "vcard-parser": "^0.2.7"
  }
}
```

So, I suppose nixpkgs should add `nix` as a propagated build input for `node2nix`?

**Comment by svanderburg** [comment]
Yes, you need the Nix package manager installed and have `nix-hash` in your PATH to make it work. Maybe I should mention this more explicitly in the README.

**Comment by svanderburg** [comment]
Closing this issue since I added I note on this in the README.md
