### ISSUE TITLE
Truly optional optionalDependencies can be broken

### ISSUE THREAD

**Issue by nicknovitski** [svanderburg/node2nix#73]
Currently, node2nix treats optionalDependencies just like dependencies, but it's not unheard of for packages to have optionalDependencies which cannot be built on all platforms.  For example, [see the apollo engine](https://github.com/apollographql/apollo-engine-js/blob/master/package.json#L29-L33).  The generated nix files for packages such as that require editing before they will build appropriately. 

The npm docs say:
> If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object.

I assume that logic cannot be duplicated in nix.  What if optional dependencies were not included by default, but node2nix had an argument `--optional-dependencies name1[,name2,...]`?

**Comment by svanderburg** [comment]
At the moment, node2nix completely ignores optionalDependencies. The main reason is indeed because there is no equivalent in Nix -- allowing the deployment of dependencies to fail, including non-deterministic failures is something that Nix does not allow.

Currently there is nothing to control optional dependencies, but it may be useful to add a feature allowing the user to control them. This is something that still needs to be developed.

**Comment by nicknovitski** [comment]
> At the moment, node2nix completely ignores optionalDependencies.

Maybe we're talking about different things.  The problem I ran into is specifically that I'm pulling in the optionalDependencies of my dependencies.  For example.

```
$ nix-shell -p nodePackages.node2nix --command 'node2nix --input <(echo "[\"exp\"]")'
# ...
$ grep 'traveling-fastlane.*{' node-packages.nix
    "@expo/traveling-fastlane-darwin-1.2.5" = {
    "@expo/traveling-fastlane-linux-1.2.5" = { 
```

[Those two packages are in exp's optionalDependencies](https://github.com/expo/exp/blob/master/package.json#L93-L96).  The generated package cannot build: either one or both of those os-specific dependencies has to be removed.

I was also misled by [this code](https://github.com/svanderburg/node2nix/blob/1b04a6d1b32c0a56fb70473a0f35e58a63f8f63e/nix/node-env.nix#L150-L154).  It looks like it's deriving a package.json with exact version specifications, including for optionalDependencies, to later be used by npm.  Is that right?

**Comment by nicknovitski** [comment]
Ah, I see: it's when I specify a lock file.

Reproduction:

```
$ git clone https://github.com/expo/exp.git
$ cd exp
$ node2nix -v
node2nix 1.5.3
$ grep optionalDependencies -A 4 package.json
  "optionalDependencies": {
    "@expo/traveling-fastlane-darwin": "1.4.7",
    "@expo/traveling-fastlane-linux": "1.4.7"
  }
}
$ node2nix -8 -i package.json
# ...
$ grep traveling-fastlane node-packages.nix
$ node2nix -8 -l package-lock.json
fetching local directory: ./. from .
$ grep traveling-fastlane node-packages.nix
    "@expo/traveling-fastlane-darwin-1.4.7" = {
      name = "_at_expo_slash_traveling-fastlane-darwin";
      packageName = "@expo/traveling-fastlane-darwin";
        url = "https://registry.npmjs.org/@expo/traveling-fastlane-darwin/-/traveling-fastlane-darwin-1.4.7.tgz";
    "@expo/traveling-fastlane-linux-1.4.7" = {
      name = "_at_expo_slash_traveling-fastlane-linux";
      packageName = "@expo/traveling-fastlane-linux";
        url = "https://registry.npmjs.org/@expo/traveling-fastlane-linux/-/traveling-fastlane-linux-1.4.7.tgz";
      sources."@expo/traveling-fastlane-darwin-1.4.7"
      sources."@expo/traveling-fastlane-linux-1.4.7"
$ nix build -A package
# ...

> @expo/traveling-fastlane-darwin@1.4.7 preinstall /nix/store/frn3rlna615psr37sb89z46a5gzbv71i-node-exp-54.0.0/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-darwin
> node platform.js


> @expo/traveling-fastlane-linux@1.4.7 preinstall /nix/store/frn3rlna615psr37sb89z46a5gzbv71i-node-exp-54.0.0/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-linux
> node platform.js

/nix/store/frn3rlna615psr37sb89z46a5gzbv71i-node-exp-54.0.0/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-linux/platform.js:3
  throw new Error('Not running on platform with Linux available');
  ^

Error: Not running on platform with Linux available
    at Object.<anonymous> (/nix/store/frn3rlna615psr37sb89z46a5gzbv71i-node-exp-54.0.0/lib/node_modules/exp/node_modules/@expo/traveling-fastlane-linux/platform.js:3:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @expo/traveling-fastlane-linux@1.4.7 preinstall: `node platform.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @expo/traveling-fastlane-linux@1.4.7 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /private/tmp/nix-build-node-exp-54.0.0.drv-0/.npm/_logs/2018-05-18T00_40_08_705Z-debug.log
builder for '/nix/store/nn5mymy7mkjyndbsvw2fgp2w0qlalxyh-node-exp-54.0.0.drv' failed with exit code 1
error: build of '/nix/store/nn5mymy7mkjyndbsvw2fgp2w0qlalxyh-node-exp-54.0.0.drv' failed
```

It seems like the packages listed in the lock file as `"optional": true` should be filtered out.

**Comment by nicknovitski** [comment]
My mistake, the problem is present without getting package-lock.json involved: nested optional dependencies are included as top-level dependencies in `node-packages.nix`.

```
$ node2nix -8 -i package.json
# ...
$ nix build -f . package
# ..
$ ls -d result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-*
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-darwin-ia32
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-darwin-x64
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-freebsd-ia32
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-freebsd-x64
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-linux-arm
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-linux-arm64
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-linux-ia32
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-linux-x64
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-sunos-x64
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-win32-ia32
result/lib/node_modules/exp/node_modules/@expo/ngrok-bin-win32-x64
$ npm ls @expo/ngrok-bin-darwin-ia32
exp@54.0.0 /Users/nick/Source/universe/dev/exp
└─┬ UNMET DEPENDENCY xdl@50.0.0
  └─┬ UNMET DEPENDENCY @expo/ngrok@2.4.2
    └─┬ UNMET DEPENDENCY @expo/ngrok-bin@2.2.8-beta.3
      └── UNMET OPTIONAL DEPENDENCY @expo/ngrok-bin-darwin-ia32@2.2.8
```

**Comment by nicknovitski** [comment]
With 3033bf4, node2nix correctly filters out all optional dependencies when given the `-l package-lock.json` option.  But the problem I mention in my comment above is still present: when given the `-i package.json` option, optional dependencies of the top-level packages' dependencies are not filtered out.  So if `foo` has a dependency `bar`, which has an optional dependency `baz`, when we run node2nix on `foo`, `baz` will be included.

The example I've been using is the package `exp`, which requires `xdl`, which requires `@expo/ngrok`, which requires `@expo/ngrok-bin`, which has a collection of optional dependencies such as `@expo/ngrok-bin/darwin-x64`.  All of those optional dependencies are included in the build result.

**Comment by svanderburg** [comment]
Hmm, this a really weird situation. It appears that when you fetch the metadata of the package from the NPM registry, e.g. by running:

```bash
$ npm info @expo/ngrok-binls
```

Then you will notice that these optionalDependencies are also declared as regular dependencies. That's the reason why they are included in the generation process.

I need to investigate whether this is a (consistent) oddity in the NPM registry or some weird side effect of the publishing process of the package. I need to find another package with an optional dependency to compare this with.

**Comment by svanderburg** [comment]
@nicknovitski It seems that this is another oddity I have to cope with -- if somebody publishes a package with an optional dependency to the NPM registry, then the optional dependencies will be added to the regular dependencies. Don't ask me why this happens, but I suspect this is probably some weird hack/workaround something the NPM people implemented.

I need to change the code in such a way that for all dependencies fetched from the NPM registry metadata, the optional dependencies must be deducted.

**Comment by svanderburg** [comment]
I made a change in revision 5bce36cf0fb54fb9da7e65bbf345ed8e0815f6f7 that removes the optional dependencies from the dependencies.

This is the weirdest work around I have ever implemented to make a package working, but I guess there is nothing else we can do.

**Comment by svanderburg** [comment]
@nicknovitski I just ran into a problem with another package whose functionality has been severely degraded by stripping out the optional dependencies. Furthermore, if I bootstrap `node2nix` itself, then the logging seems to be missing, since this functionality is also provided by an optional dependency (`npmlog`). No logging output means that you can't see what `node2nix` is doing.

I think I need to revert to the old behaviour and make removing the optional dependencies an optional feature that can be enabled by a feature flag.

I should also add a new section to the the `README.md` file, with some troubleshooting tricks. It seems that removing optional dependencies in some scenarios fixes broken packages and in others it degrades the functionality of packages in such a way that they become unusable.

**Comment by svanderburg** [comment]
@nicknovitski I now made stripping optional dependencies an optional feature (see the brand new 'Troubleshooting' section in the README.md file). The default behaviour remains that they get included. I think in the majority of cases it causes problems, include node2nix itself -- the npmlog module won't get included and as a result, you can't see any output.

**Comment by nicknovitski** [comment]
Yeah, I agree.  The `exp` package is another example, there are features which won't work if it doesn't install at least one `ngrok-bin-*` package.

yarn2nix seems to solve this by deferring to yarn: all optional dependencies are downloaded by nix to an offline cache derivation, then yarn is run against that offline cache.  Yarn detects if any packages in that cache are incompatible with the host system, and then doesn't install them to the top-level package's node_modules.

Is a solution like that possible for node2nix?
