### ISSUE TITLE
How to override dependencies of package

### ISSUE THREAD

**Issue by srghma** [svanderburg/node2nix#84]
In documentation there is only info how to override dependencies for collection of packages https://github.com/svanderburg/node2nix#adding-unspecified-dependencies, but how to override dependency of one package?

For example, I want to fix this issue here https://github.com/srghma/my-create-react-app/tree/105064cbb5ac9a5a34f4b6da2d07385d5785e8a1 

```sh
$ nix-shell 
..........
Adding metadata fields to: node_modules/y18n/package.json
Adding metadata fields to: node_modules/yallist/package.json
Adding metadata fields to: node_modules/yargs/package.json
Adding metadata fields to: node_modules/yargs-parser/package.json
Adding metadata fields to: node_modules/yauzl/package.json
Adding metadata fields to: node_modules/zip-stream/package.json

> mozjpeg@4.1.1 postinstall /nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/mozjpeg
> node lib/install.js

/nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/onetime/index.js:7
                throw new TypeError('The second argument is now an options object');
                ^

TypeError: The second argument is now an options object
    at module.exports (/nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/onetime/index.js:7:9)
    at module.exports (/nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/each-async/index.js:44:37)
    at Download.run (/nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/download/index.js:115:2)
    at BinWrapper.download (/nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/bin-wrapper/index.js:217:4)
    at BinWrapper.<anonymous> (/nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/node_modules/bin-wrapper/index.js:178:9)
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozjpeg@4.1.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozjpeg@4.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /nix/store/q5wfps9n8q5sybjnpnpwjgd48nnzjrc0-node-dependencies-extension-0.0.1/extension/.npm/_logs/2018-04-29T11_50_40_141Z-debug.log
builder for '/nix/store/rh9dzz5xzf0ma775kkhn6gp6ql4l4f38-node-dependencies-extension-0.0.1.drv' failed with exit code 1
error: build of '/nix/store/rh9dzz5xzf0ma775kkhn6gp6ql4l4f38-node-dependencies-extension-0.0.1.drv' failed

```

What I need is to subsctitute mozjpeg here https://github.com/srghma/my-create-react-app/blob/105064cbb5ac9a5a34f4b6da2d07385d5785e8a1/nix/node-output.nix#L7891 with mozjpeg from nixpkgs, how to do this?

**Comment by svanderburg** [comment]
It's not possible to "override" a dependency or transitive NPM dependency by providing parameters to a Nix expression.

What you can do is using the `preRebuild` hook (see the README.md for more info) to modify the generated `node_modules/` folder and use that, for example, to replace a dependency or alter it.

It's not very elegant, but it offers enough freedom to make the changes that you need.
