### ISSUE TITLE
Google cloud functions emulator

### ISSUE THREAD

**Issue by xnaveira** [svanderburg/node2nix#87]
Trying to create a development environment for Google Cloud Functions. There is a node module `@google-cloud/functions-emulator` which provides the binary `functions` which is a local emulator for Google Cloud Functions (similar to AWS lambda functions). This local emulator provides a faster development cycle. Once installed the `functions start` command must be issued in order to start the emulator. The manual specifies that hte package must be installed using `npm install -g`. In order to be able to use it in NixOS the following steps were followed:

Create `package.json`:
```json
{
  "name": "trackitone",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "eslint index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "busboy": "^0.2.14"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.12.0"
  }
}
```
Create `supplement.json`:
```json
[
  "@google-cloud/functions-emulator"
]
```
Run: 
	```node2nix -6 -d -i package.json --development --supplement-input supplement.json -l```

And then enter the shell:
        ```nix-shell -A shell```

When running `functions start` inside the shel i get:
```
Google Cloud Functions Emulator RUNNING
ERROR: Error: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: mime.lookup is not a function<br> &nbsp; &nbsp;at ServerResponse.contentType (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:592:12)<br> &nbsp; &nbsp;at ServerResponse.send (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:145:14)<br> &nbsp; &nbsp;at Object.sendRestError (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/src/utils/errors.js:155:21)<br> &nbsp; &nbsp;at RestService.server.use (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/src/service/rest-service.js:108:53)<br> &nbsp; &nbsp;at Layer.handle_error (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/layer.js:71:5)<br> &nbsp; &nbsp;at trim_prefix (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:315:13)<br> &nbsp; &nbsp;at /nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at next (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/route.js:127:14)</pre>
</body>
</html>

    at RequestError.Error (native)
    at new RequestError (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:108:23)
    at Request.self.callback (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/nix/store/kbmjjz60b14biy1xmp84f68wdfq6y7jb-node-_at_google-cloud_slash_functions-emulator-1.0.0-beta.4/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1079:12)
```

**Comment by svanderburg** [comment]
Maybe this is related to issue #90 

Can you try installing the latest development version and see if this works for you?

**Comment by svanderburg** [comment]
I now released node2nix 1.6.0 that contains a bugfix for the dependency resolution algorithm. Can you try it?
